#!/usr/bin/env node

/*jslint
    node
*/

"use strict";

function highlight(str) {
    return String.fromCharCode(27) + "[7m" + str +
            String.fromCharCode(27) + "[27m";
}

function highlightCol(str, i) {
    const c = str.charAt(i);
    const code = str.charCodeAt(i);

    // Handle non-BMP characters
    if (code >= 0xD800 && code <= 0xDBFF) {
        const codeAfter = str.charCodeAt(i + 1);
        if (codeAfter >= 0xDC00 && codeAfter <= 0xDFFF) {
            return str.slice(0, i) + highlight(c + str.charAt(i + 1)) +
                    str.slice(i + 2);
        }
    } else if (code >= 0xDC00 && code <= 0xDFFF && i !== 0) {
        const codeBefore = str.charCodeAt(i - 1);
        if (codeBefore >= 0xD800 && codeBefore <= 0xDBFF) {
            return str.slice(0, i - 1) + highlight(str.charAt(i - 1) + c) +
                    str.slice(i + 1);
        }
    }
    return str.slice(0, i) + highlight(c) + str.slice(i + 1);
}

function paddedNumber(totalSpace, number) {
    const digitString = number.toString();
    const padding = totalSpace - digitString.length;
    const space = " ";

    if (padding >= 0) {
        return space.repeat(padding) + digitString;
    } else {
        return digitString;
    }
}

function displayErrors(path, data) {
    const fudge = Number(Boolean(data.option.fudge));
    const maxerr = data.option.maxerr;
    const numberOfWarnings = data.warnings.length;
    const tooMany = numberOfWarnings >= maxerr;
    const tooManyNumber = numberOfWarnings - tooMany;
    const tooManyNumberDigits = tooManyNumber.toString().length;
    const unable = "JSLint was unable to finish.";

    if (numberOfWarnings !== 0) {
        console.log("\n%s", path);
        const maxLine = data.warnings[numberOfWarnings - 1].line + fudge;
        const maxLineDigits = maxLine.toString().length;

        data.warnings.forEach(function (warning, i) {
            const message = warning.message;

            if (i === maxerr && data.stop) {
                console.log(" ", message, unable);
            } else {
                const messageCol = warning.column;
                const messageColHi = highlightCol(
                    data.lines[warning.line],
                    messageCol
                );
                const messageLine = warning.line + fudge;
                const messageLineHi = highlight(
                    paddedNumber(maxLineDigits, messageLine)
                );
                const messageNum = paddedNumber(tooManyNumberDigits, i + 1);
                console.log("  #%s %s", messageNum, message);
                console.log("  %s %s", messageLineHi, messageColHi);
            }
        });
    }
    if (data.stop && !tooMany) {
        console.log(" ", unable);
    }
}

function parseCommandLineArgs(argv) {
    var notStop = true;
    const optRegEx = /^--([^\s=]+)(?:=(\S*))?$/;

    return argv.reduce(function (conf, arg) {
        if (notStop) {
            if (arg === "--") {
                notStop = false;
                return conf;
            }

            const match = arg.match(optRegEx);
            if (match) {
                const key = match[1];
                const value = match[2];

                switch (key) {
                case "bitwise":
                case "browser":
                case "convert":
                case "couch":
                case "devel":
                case "eval":
                case "for":
                case "fudge":
                case "getset":
                case "multivar":
                case "node":
                case "single":
                case "this":
                case "white":
                    switch (value) {
                    case "true":
                    case undefined:
                        conf.options[key] = true;
                        break;
                    case "false":
                        conf.options[key] = false;
                        break;
                    default:
                        throw new Error(
                            "'" + key + "' must have a Boolean value."
                        );
                    }
                    return conf;
                case "maxerr":
                case "maxlen":
                    conf.options[key] = Number.parseInt(value);
                    if (Number.isNaN(conf.options[key])) {
                        throw new Error(
                            "'" + key + "' must have a numeric value."
                        );
                    }
                    return conf;
                case "raw":
                case "sha-bang":
                case "version":
                    if (value !== undefined) {
                        throw new Error(
                            "'" + key + "' does not expect a value."
                        );
                    }
                    conf.flags[key] = true;
                    return conf;
                default:
                    throw new Error("Unexpected option: '" + key + "'.");
                }
            }
        }

        conf.filePaths.push(arg);
        return conf;
    }, {
        filePaths: [],
        flags: {
            raw: false,
            "sha-bang": false,
            version: false
        },
        options: {}
    });
}

const {jslintEdition, jslintFile} = require("./index");
var flags;
var filePaths;
var cmdLineOpts;
var parsedArgs;

function printErrorAndExit(err) {
    console.error(err.toString());
    process.exit(1);
}

try {
    parsedArgs = parseCommandLineArgs(process.argv.slice(2));
} catch (err) {
    printErrorAndExit(err);
}

filePaths = parsedArgs.filePaths;
cmdLineOpts = parsedArgs.options;
flags = parsedArgs.flags;

if (flags.version) {
    const version = require("./package.json").version;
    if (flags.raw) {
        process.stdout.write(JSON.stringify({
            version: version,
            jslintEdition: jslintEdition
        }));
    } else {
        console.log(
            "jslint (JSLinter) %s (JSLint edition %s)",
            version,
            jslintEdition
        );
        console.log("Copyright (c) 2015-2018 Nicola Squartini");
    }
    process.exit(0);
}

if (filePaths.length === 0) {
    printErrorAndExit("No files specified.");
}

jslintFile(filePaths, {
    callback: flags.raw
        ? function ({pathname, report}) {
            return {
                file: pathname,
                option: report.option,
                stop: report.stop,
                warnings: report.warnings
            };
        }
        : function ({pathname, report}) {
            displayErrors(pathname, report);
        },
    options: cmdLineOpts,
    shaBang: flags["sha-bang"]
}).then(function (out) {
    if (flags.raw) {
        process.stdout.write(JSON.stringify(out));

    }
}).catch(printErrorAndExit);
